### ISSUE TITLE
PerceptualSimilarity

### ISSUE THREAD

**Issue by LeArmadillo** [zhengyuf/STED-gaze#5]
Hi Zhengyuf,

The train_st_ed.py script is looking for a folder PerceptualSimilarity, can you provide the source for this?  

STED-gaze-master# python train_st_ed.py config/eval.json
Traceback (most recent call last):
  File "train_st_ed.py", line 20, in <module>
    from models import STED
  File "/translation/STED-gaze-master/models/__init__.py", line 2, in <module>
    from .st_ed import STED
  File "/translation/STED-gaze-master/models/st_ed.py", line 27, in <module>
    from .PerceptualSimilarity.lpips_models import PerceptualLoss
ModuleNotFoundError: No module named 'models.PerceptualSimilarity'

**Comment by LeArmadillo** [comment]
Also seem to be missing DisModel():


Traceback (most recent call last):
  File "train_st_ed.py", line 119, in <module>
    network = STED().to(device)
  File "/translation/STED-gaze-master/models/st_ed.py", line 80, in __init__
    self.lpips = PerceptualLoss(model='net-lin', net='alex').to("cuda")
  File "/translation/STED-gaze-master/models/st_ed.py", line 43, in __init__
    self.model = dist_model.DistModel()
NameError: name 'dist_model' is not defined

**Comment by zhengyuf** [comment]
hey, the perceptual similarity model is from this repo: https://github.com/richzhang/PerceptualSimilarity
I've updated my code to work with theirs :)
Just pull the updates and install lpips with pip, and it should be fine now.

**Comment by zhengyuf** [comment]
as for the problem with DisModel, i don't think i used that, and i cannot find it on the 43rd line of st_ed.py.

**Comment by LeArmadillo** [comment]
Thanks! That fixed it
